name: CI/CD Secure TODO App

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  IMAGE_NAME: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/todo-app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-scan-push-sign:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # required for keyless Cosign signing
      packages: write

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Login to Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Build & Push Docker Image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_NAME }}:latest

      # 5. Scan image with Trivy
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: 'table'
          vuln-type: 'os,library'
          ignore-unfixed: true
          exit-code: '1'   # fail workflow on critical vulnerabilities

      # 6. Install Cosign
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      # 7. Sign the image (keyless, via GitHub OIDC)
      - name: Sign Docker image with Cosign (keyless)
        run: |
          cosign sign ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --yes

      # 8. Verify the signature
      - name: Verify Docker image signature
        run: |
          cosign verify ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

